name: tic_tac_app
description: Application Food.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  liquid_swipe: ^1.1.0
  get_it: ^4.0.2
  provider: ^4.0.4
  http: 0.12.0+2
  google_fonts: ^1.1.0
  font_awesome_flutter: ^8.8.1
  firebase_auth: ^0.16.0
  google_sign_in: ^4.3.0
  email_validator: ^1.0.0
  cloud_firestore: ^0.13.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
  - assets/images/bestfood/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
