name: tic_tac_app
description: Application Food.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_core:
  http: 0.12.0+2
  google_fonts: ^1.1.0
  font_awesome_flutter: ^8.8.1
  firebase_auth:
  google_sign_in: ^4.3.0
  email_validator: ^1.0.0
  cloud_firestore:
  lottie: ^0.4.0+1
  barcode_scan: 1.0.0
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.1.4+2
  liquid_swipe: ^1.5.0
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
  - assets/images/
  - assets/animations/
  - assets/icons/
  - assets/images/menus/
  - assets/images/topmenu/
  - assets/images/popular_foods/
  - assets/images/bestfood/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
